apiVersion: v1
kind: Service
metadata:
  name: wiki-service
  labels:
    app: gwiki-service
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.79.197
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywiki
  sessionAffinity: None